import { Food } from "./app/shread/models/food";

export const sample_foods: any[] = [
  {
    id: '1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 150,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/images/pizza.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '2',
    name: 'Meatball',
    price: 90,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: 'assets/images/Meatballs-spoon.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '3',
    name: 'Hamburger',
    price: 80,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'assets/images/Hamburger.webp',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '4',
    name: 'Biriyani',
    price: 350,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'assets/images/biriyani.webp',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '5',
    name: 'Chicken Soup',
    price: 90,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'assets/images/Chicken Soup.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '6',
    name: 'chili chicken',
    price: 120,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/images/chili chicken.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  // new item
  {
    id: '7',
    name: 'freanch fry',
    price: 69,
    cookTime: '10-20',
    favorite: true,
    origins: ['India,Bangladesh'],
    stars: 4.0,
    imageUrl: 'assets/images/crispyrench.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '8',
    name: 'boneless chicken sauce',
    price: 159,
    cookTime: '40-50',
    favorite: false,
    origins: ['India,us'],
    stars: 4.0,
    imageUrl: 'assets/images/boneless-chickensauce.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '9',
    name: 'palak panir',
    price: 59,
    cookTime: '20-30',
    favorite: true,
    origins: ['India,pakisthan'],
    stars: 4.0,
    imageUrl: 'assets/images/palakpanir.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '10',
    name: 'penne pasta',
    price: 99,
    cookTime: '20-30',
    favorite: false,
    origins: ['India,maxiko'],
    stars: 4.0,
    imageUrl: 'assets/images/pennepasta.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '10',
    name: 'chickenTanduri',
    price: 499,
    cookTime: '40-50',
    favorite: true,
    origins: ['India,us'],
    stars: 4.0,
    imageUrl: 'assets/images/chickenTanduri.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '10',
    name: 'momos',
    price: 99,
    cookTime: '10-20',
    favorite: true,
    origins: ['India,nepal'],
    stars: 4.0,
    imageUrl: 'assets/images/momos.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },

]
export const sample_tags: any[] = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
]